Feature/model/list
WildCodeSchool/tlse-php-202109-p2-wishlist pull request #40
Opened 2021-11-09 16:06 UTC by AsaseYa

2021-11-09 16:30 UTC, AsaseYa commented on database/DB.sql
>  /*!40000 ALTER TABLE `list` ENABLE KEYS */;
on a pas encore traduit la date =)

2021-11-09 16:50 UTC, nicopierresanchez approved these changes

2021-11-10 08:30 UTC, bastienwcs requested changes

2021-11-10 08:30 UTC, bastienwcs commented on src/routes.php
> +/*    'list/share' => ['ListController', 'share',],*/
pas de code mort

2021-11-10 08:36 UTC, AsaseYa commented on src/routes.php
> +/*    'list/share' => ['ListController', 'share',],*/
Corrigé !

2021-11-10 08:37 UTC, bastienwcs approved these changes

2021-11-10 08:37 UTC, merged